"""Stage 8 / Phase 5 visualisation: convert the dataset .npz into an OBJ
mesh sequence that any 3D modelling software can open.

Reads `outputs/<date> - dataset [<tag>].npz` (from 10_export_dataset.py)
and writes a directory of per-frame `.obj` files plus a couple of static
helper meshes (table plane + marker outline) and a README.md with
import instructions.

Output layout:

    outputs/<date> - mesh sequence [<tag>]/
        README.md                Import instructions for Blender / Maya / etc.
        scene.obj                Table plane (1 m × 1 m) + marker outline,
                                 both at Z=0 in table frame. Static.
        mesh_0000.obj            Frame 0: up to 2 hand meshes (slots 0, 1).
        mesh_0001.obj            Frame 1.
        ...                      ...
        mesh_NNNN.obj            Last frame.

Each per-frame OBJ contains up to two hand meshes (slot 0 = orange in our
viz, slot 1 = blue) with MANO topology — 778 vertices, 1538 triangles
per hand. Hands that weren't anchored that frame are simply omitted from
the OBJ (so frame mesh count varies). For animation playback in Blender,
the Stop Motion OBJ addon handles variable topology cleanly; see the
generated README.md for setup.

Coordinate frame: **table frame**, metric metres. (0, 0, 0) is the
marker centre. +Z is up from the table.

Run:
  .venv/bin/python scripts/viz/export_obj_sequence.py
  .venv/bin/python scripts/viz/export_obj_sequence.py --max-frames 100
  .venv/bin/python scripts/viz/export_obj_sequence.py \\
      --dataset "outputs/<date> - dataset [foo].npz" \\
      --tag    "foo"
"""

import argparse
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "_lib"))
from dated import today_pretty


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_DATASET = (PROJECT_ROOT
    / "outputs/30th April 2026 - dataset [20260430 manipulation].npz")
DEFAULT_TAG = "20260430 manipulation"


def from_root(p):
    p = Path(p)
    return p if p.is_absolute() else (PROJECT_ROOT / p).resolve()


def write_obj(path: Path, objects):
    """Write an OBJ file with one or more named objects.

    `objects` is a list of (name, vertices, faces) tuples.
    Vertices are (V, 3) float arrays in metres.
    Faces are (F, 3) int arrays of 0-indexed vertex indices.

    OBJ stores 1-indexed vertex indices and accumulates them across
    objects in the same file, so we offset face indices by the running
    vertex count.
    """
    lines = []
    lines.append("# Auto-generated by scripts/viz/export_obj_sequence.py")
    lines.append("# Coordinate frame: table frame, metric metres.")
    lines.append("# (0, 0, 0) is the marker centre on the table; +Z is up from the table.")
    v_offset = 0
    for name, verts, faces in objects:
        lines.append(f"o {name}")
        for v in verts:
            lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
        for tri in faces:
            lines.append(
                f"f {int(tri[0]) + v_offset + 1} "
                f"{int(tri[1]) + v_offset + 1} "
                f"{int(tri[2]) + v_offset + 1}"
            )
        v_offset += verts.shape[0]
    path.write_text("\n".join(lines) + "\n")


def write_scene_obj(path: Path, marker_size_m: float = 0.080,
                    table_half_m: float = 0.5):
    """Static helper: a 1 m × 1 m table plane at Z=0 + a small marker
    outline at the origin. Lets the user pull a single 'scene' file into
    their DCC tool to anchor the visual context for the hand sequence."""
    h = table_half_m
    table_verts = np.array([
        [-h, -h, 0],
        [+h, -h, 0],
        [+h, +h, 0],
        [-h, +h, 0],
    ], dtype=np.float64)
    table_faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int32)

    s = marker_size_m / 2.0
    marker_verts = np.array([
        [-s, -s, 0.001],   # 1 mm above table so it's visible on top of the plane
        [+s, -s, 0.001],
        [+s, +s, 0.001],
        [-s, +s, 0.001],
    ], dtype=np.float64)
    marker_faces = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.int32)

    write_obj(path, [
        ("table_plane", table_verts, table_faces),
        ("marker_outline", marker_verts, marker_faces),
    ])


README_TEMPLATE = """# Mesh sequence — {tag}

Generated by `scripts/viz/export_obj_sequence.py` from
`{source}`.

## Contents

- `scene.obj` — static helper: 1 m × 1 m table plane at Z=0, plus a 8 cm
  marker outline at the origin. Import once for visual context.
- `mesh_NNNN.obj` ({n_frames} frames at {fps:.1f} fps, ~{duration:.1f} s) — per-frame
  hand meshes. Each file contains up to two named objects:
  `hand_slot0` (the leftmost-by-X hand in the source video) and `hand_slot1`.
  Frames where a hand wasn't tracked simply omit that object.

Hand meshes follow MANO topology: 778 vertices, 1538 triangles per hand.

## Coordinate frame

**Table frame, metric metres.** (0, 0, 0) is the marker centre on the
table. +Z is up from the table surface. Set your DCC tool's scene units
to metres.

## Open in Blender

### Easiest — Stop Motion OBJ addon

1. Install the [Stop Motion OBJ](https://github.com/neverhood311/Stop-motion-OBJ)
   addon (free, in the Blender extension menu or downloadable from GitHub).
2. File → Import → Mesh Sequence...
3. Point at this directory, set the file pattern to `mesh_*.obj`, and
   set the playback frame rate to **{fps:.0f} fps**.
4. Import `scene.obj` separately (File → Import → Wavefront (.obj)) for
   the table + marker reference.

### Manual via Python (no addon)

Paste into Blender's Python console:

```python
import bpy
from pathlib import Path

seq_dir = Path("/absolute/path/to/this/directory")
for f in sorted(seq_dir.glob("mesh_*.obj")):
    bpy.ops.wm.obj_import(filepath=str(f))

# Then keyframe visibility per frame manually, or animate via the
# Mesh Cache modifier on a base mesh.
```

## Animation timing

Frame `mesh_NNNN.obj` corresponds to time `NNNN / {fps:.0f}` seconds since the
start of the source clip.

Set the scene render fps to **{fps:.0f}** to play back at real-time speed.

## What's where

The hand meshes are oriented anatomically: looking down at the table
from above, with +Z pointing up at the camera. The marker on the table
is at (0, 0, 0). Hand positions on the table appear in the +X / +Y
plane (approximately; the marker's chirality defines the +X axis of the
table).

This is the **K-anchored metric mesh** from the canonical pipeline —
positions are stereo-correct (the wrist is metric), but the mesh size is
uniformly scaled by the per-frame `k ≈ 0.78` factor so the wrist matches
stereo. To get the WiLoR-monocular-sized mesh instead (slightly larger),
rebuild from `mano_pose` + `mano_betas` in the parent `.npz` via the
MANO model, then translate by `wrist_table[i, slot]`.

## Provenance

- `schema_version`: {schema_version}
- `source_canonical`: {source_canonical}
- `source_anchor`: {source_anchor}
- `source_calibration`: {source_calibration}
- `generated_on`: {generated_on}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", default=str(DEFAULT_DATASET),
                    help="Phase 5 dataset .npz from 10_export_dataset.py")
    ap.add_argument("--tag", default=DEFAULT_TAG, help="output directory tag")
    ap.add_argument("--max-frames", type=int, default=None,
                    help="export only the first N frames (smoke testing)")
    args = ap.parse_args()

    dataset_path = from_root(args.dataset)
    if not dataset_path.is_file():
        sys.exit(f"missing dataset: {dataset_path}")
    print(f"dataset: {dataset_path.name}")

    d = np.load(dataset_path, allow_pickle=True)
    for key in ("vertices_table", "hand_present", "mano_faces", "fps",
                "schema_version", "source_canonical", "source_anchor",
                "source_calibration", "generated_on"):
        if key not in d.files:
            sys.exit(f"dataset npz missing key {key!r}")

    vertices_table = d["vertices_table"]   # (N, 2, 778, 3)
    hand_present = d["hand_present"]        # (N, 2)
    mano_faces = d["mano_faces"]            # (1538, 3)
    fps = float(d["fps"])
    n_total = vertices_table.shape[0]
    n = min(n_total, args.max_frames) if args.max_frames else n_total
    n_slot = vertices_table.shape[1]
    duration = n / fps
    print(f"frames: {n} ({duration:.1f} s @ {fps:.1f} fps), slots: {n_slot}")

    out_dir = PROJECT_ROOT / f"outputs/{today_pretty()} - mesh sequence [{args.tag}]"
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"writing to: {out_dir}")

    # Static scene helper.
    write_scene_obj(out_dir / "scene.obj")

    # Per-frame meshes.
    width = max(4, len(str(n - 1)))
    n_with_hands = 0
    n_empty = 0
    t0 = time.time()
    for i in range(n):
        objects = []
        for s in range(n_slot):
            if not hand_present[i, s]:
                continue
            verts = vertices_table[i, s]
            if np.any(np.isnan(verts)):
                continue
            objects.append((f"hand_slot{s}", verts, mano_faces))
        if objects:
            n_with_hands += 1
        else:
            n_empty += 1
        path = out_dir / f"mesh_{i:0{width}d}.obj"
        write_obj(path, objects)
        if (i + 1) % 60 == 0 or i == n - 1:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed if elapsed else 0
            sys.stdout.write(f"\rframe {i+1}/{n}  {rate:.0f} obj/s   ")
            sys.stdout.flush()
    print()

    # README with instructions + provenance.
    readme = README_TEMPLATE.format(
        tag=args.tag,
        source=dataset_path.name,
        n_frames=n,
        fps=fps,
        duration=duration,
        schema_version=str(d["schema_version"]),
        source_canonical=Path(str(d["source_canonical"])).name,
        source_anchor=Path(str(d["source_anchor"])).name,
        source_calibration=Path(str(d["source_calibration"])).name,
        generated_on=str(d["generated_on"]),
    )
    (out_dir / "README.md").write_text(readme)

    # Summary
    total_size = sum(f.stat().st_size for f in out_dir.glob("*.obj"))
    print()
    print(f"=== mesh sequence written → {out_dir.name}/ ===")
    print(f"frames with hands: {n_with_hands}")
    print(f"empty frames:      {n_empty} (no hand tracked)")
    print(f"total OBJ size:    {total_size / (1024 * 1024):.1f} MB "
          f"({total_size / max(n, 1) / 1024:.1f} KB / frame)")
    print()
    print(f"Open {out_dir / 'README.md'} for import instructions.")


if __name__ == "__main__":
    main()
